language: csharp
solution: DNDGenSite.sln
before_install:
  - sudo add-apt-repository ppa:ubuntu-wine/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install wine1.7 -y
install:
  - nuget restore DnDGen.Web.sln
  - nuget install NUnit.Runners -OutputDirectory testrunner
  - nuget install Chutzpah -OutputDirectory testrunner
script:
  - xbuild DnDGen.Web.sln /p:TargetFrameworkVersion="v4.5.1" /p:Configuration=Release
  - set -e
  - mono ./testrunner/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./DnDGen.Web.Tests.Unit/bin/Release/DnDGen.Web.Tests.Unit.dll
  - set -e
  - mono ./testrunner/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./DnDGen.Web.Tests.Integration/bin/Release/DnDGen.Web.Tests.Integration.dll
  - set -e
  - mono ./testrunner/Chutzpah.*/tools/chutzpah.console.exe ./DnDGen.Web.Tests.Unit/Scripts
