language: csharp
mono:
  - 5.2.0
solution: DnDGen.Web.sln
install:
  - nuget restore DnDGen.Web.sln
  - nuget install NUnit.Runners -OutputDirectory testrunner
script:
  - xbuild DnDGen.Web.sln /p:TargetFrameworkVersion="v4.5.1" /p:Configuration=Release
  - set -e
  - mono ./testrunner/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./DnDGen.Web.Tests.Unit/bin/Release/DnDGen.Web.Tests.Unit.dll
  - set -e
  - mono ./testrunner/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./DnDGen.Web.Tests.Integration/bin/Release/DnDGen.Web.Tests.Integration.dll
